import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8F9FA",
      },
      // Header
      header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#062C41",
        paddingTop: Platform.OS === 'ios' ? 50 : 38,
        paddingBottom: 16,
        paddingHorizontal: 16,
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
      },
      profileContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        marginLeft: 8,
      },
      headerAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 2,
        borderColor: "#FFFFFF",
      },
      avatarPlaceholder: {
        backgroundColor: "#C4C4C4",
        alignItems: "center",
        justifyContent: "center",
      },
      avatarInitial: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#FFFFFF",
      },
      userInfoContainer: {
        marginLeft: 12,
      },
      headerName: {
        fontSize: 18,
        fontWeight: "700",
        color: "#FFFFFF",
        letterSpacing: 0.3,
      },
      userStatus: {
        fontSize: 13,
        color: "rgba(255, 255, 255, 0.9)",
        marginTop: 2,
      },
      reportButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
      },
      // Liste de messages
      messagesList: {
        flex: 1,
        paddingHorizontal: 10,
      },
      messagesContainer: {
        paddingTop: 10,
        paddingBottom: 16,
      },
      dateHeaderContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginVertical: 16,
        paddingHorizontal: 16,
      },
      dateHeaderLine: {
        flex: 1,
        height: 1,
        backgroundColor: "rgba(0, 0, 0, 0.08)",
      },
      dateHeader: {
        fontSize: 13,
        fontWeight: "500",
        color: "#757575",
        marginHorizontal: 8,
        textAlign: "center",
      },
      messageContainer: {
        flexDirection: "row",
        alignItems: "flex-end",
        marginBottom: 2,
        paddingHorizontal: 8,
        paddingVertical: 4,
      },
      sentMessageContainer: {
        justifyContent: "flex-end",
      },
      receivedMessageContainer: {
        justifyContent: "flex-start",
      },
      consecutiveSentMessage: {
        marginTop: -2,
        marginBottom: 2,
      },
      consecutiveReceivedMessage: {
        marginTop: -2,
        marginBottom: 2,
      },
      messageAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        marginHorizontal: 8,
      },
      avatarSpaceholder: {
        width: 32,
        marginHorizontal: 8,
      },
      messageBubble: {
        maxWidth: "70%",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 18,
        elevation: 1,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
      },
      sentMessage: {
        backgroundColor: "#E6F2FF",
        borderBottomRightRadius: 4,
      },
      receivedMessage: {
        backgroundColor: "#FFFFFF",
        borderBottomLeftRadius: 4,
      },
      consecutiveSentBubble: {
        borderBottomRightRadius: 18,
      },
      consecutiveReceivedBubble: {
        borderBottomLeftRadius: 18,
      },
      messageText: {
        fontSize: 16,
        color: "#333333",
        lineHeight: 22,
      },
      messageFooter: {
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        marginTop: 4,
      },
      timestamp: {
        fontSize: 11,
        color: "#9E9E9E",
      },
      readStatusContainer: {
        marginLeft: 6,
      },
      readIcon: {
        marginTop: 1,
      },
      // Input container
      inputContainer: {
        marginBottom: 25,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: "#F8F9FA",
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
      },
      inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 24,
        paddingLeft: 16,
        paddingRight: 8,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
      },
      input: {
        flex: 1,
        minHeight: 40,
        maxHeight: 100,
        fontSize: 16,
        color: "#333333",
        paddingVertical: 8,
      },
      sendButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#3E64FF",
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 8,
      },
      sendButtonDisabled: {
        backgroundColor: "#CACACA",
      },
      // Modal de signalement
      modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
      },
      modalContainer: {
        width: "90%",
        maxWidth: 400,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
      },
      modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.08)",
        paddingVertical: 16,
        paddingHorizontal: 20,
      },
      modalTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#333333",
      },
      modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
      },
      modalBody: {
        padding: 20,
      },
      modalDescription: {
        fontSize: 14,
        color: "#666666",
        marginBottom: 16,
        lineHeight: 20,
      },
      reportInput: {
        backgroundColor: "#F8F9FA",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.08)",
        padding: 12,
        fontSize: 16,
        height: 120,
        color: "#333333",
      },
      modalFooter: {
        flexDirection: "row",
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        padding: 16,
      },
      cancelButton: {
        flex: 1,
        height: 48,
        borderRadius: 8,
        backgroundColor: "#F8F9FA",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 8,
      },
      cancelButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#757575",
      },
      confirmButton: {
        flex: 1,
        height: 48,
        borderRadius: 8,
        backgroundColor: "#FF5252",
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 8,
      },
      confirmButtonDisabled: {
        backgroundColor: "#FFCDD2",
      },
      confirmButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#FFFFFF",
      },
    });