import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor: "#F5F5F5",
        },
        header: {
          paddingBottom: 20,
          borderBottomLeftRadius: 24,
          borderBottomRightRadius: 24,
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.15,
          shadowRadius: 8,
          elevation: 8,
        },
        headerContent: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
          paddingHorizontal: 20,
          paddingTop: 10,
        },
        menuButton: {
          width: 40,
          height: 40,
          borderRadius: 20,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          alignItems: "center",
          justifyContent: "center",
        },
        headerTitle: {
          fontSize: 22,
          fontWeight: "700",
          color: "#FFFFFF",
          letterSpacing: 0.5,
        },
        backButton: {
          width: 40,
          height: 40,
          borderRadius: 20,
          backgroundColor: "rgba(255, 255, 255, 0.2)",
          alignItems: "center",
          justifyContent: "center",
        },
        scrollView: {
          flex: 1,
        },
        scrollContent: {
          padding: 20,
        },
        statsCard: {
          borderRadius: 16,
          padding: 20,
          marginBottom: 24,
          borderWidth: 1,
          borderColor: "rgba(255, 152, 0, 0.2)",
        },
        statsContent: {
          flexDirection: "row",
          alignItems: "center",
        },
        statsTextContainer: {
          marginLeft: 16,
        },
        statsValue: {
          fontSize: 32,
          fontWeight: "700",
          color: "#0A0A0A",
        },
        statsLabel: {
          fontSize: 14,
          color: "#737373",
          marginTop: 4,
        },
        commentCard: {
          borderRadius: 16,
          padding: 16,
          marginBottom: 16,
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
          elevation: 3,
        },
        commentHeader: {
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 12,
        },
        commentHeaderLeft: {
          flexDirection: "row",
          alignItems: "center",
        },
        commentDate: {
          fontSize: 13,
          color: "#737373",
          marginLeft: 8,
        },
        likesContainer: {
          flexDirection: "row",
          alignItems: "center",
          backgroundColor: "rgba(255, 65, 108, 0.1)",
          paddingHorizontal: 10,
          paddingVertical: 4,
          borderRadius: 12,
        },
        likesCount: {
          fontSize: 13,
          fontWeight: "600",
          color: "#FF416C",
          marginLeft: 6,
        },
        commentText: {
          fontSize: 15,
          color: "#0A0A0A",
          lineHeight: 22,
          marginBottom: 12,
        },
        postInfoContainer: {
          backgroundColor: "rgba(255, 152, 0, 0.05)",
          padding: 12,
          borderRadius: 12,
          marginBottom: 12,
          borderLeftWidth: 3,
          borderLeftColor: "#FF9800",
        },
        postInfoHeader: {
          flexDirection: "row",
          alignItems: "center",
          marginBottom: 6,
        },
        postInfoLabel: {
          fontSize: 12,
          color: "#737373",
          marginLeft: 6,
        },
        postAuthor: {
          fontWeight: "700",
          color: "#FF9800",
        },
        postContent: {
          fontSize: 13,
          color: "#262626",
          fontStyle: "italic",
        },
        viewPostButton: {
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "flex-end",
          paddingTop: 8,
        },
        viewPostText: {
          fontSize: 13,
          fontWeight: "600",
          color: "#FF9800",
          marginRight: 6,
        },
        emptyContainer: {
          alignItems: "center",
          justifyContent: "center",
          paddingVertical: 60,
        },
        emptyTitle: {
          fontSize: 20,
          fontWeight: "700",
          color: "#0A0A0A",
          marginTop: 16,
          marginBottom: 8,
        },
        emptyText: {
          fontSize: 14,
          color: "#737373",
          textAlign: "center",
        },
        loadingContainer: {
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "#F5F5F5",
        },
        loadingText: {
          marginTop: 16,
          fontSize: 16,
          color: "#737373",
        },
        errorContainer: {
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "#F5F5F5",
          padding: 20,
        },
        errorTitle: {
          fontSize: 24,
          fontWeight: "700",
          color: "#F44336",
          marginTop: 16,
          marginBottom: 8,
        },
        errorText: {
          fontSize: 14,
          color: "#737373",
          textAlign: "center",
          marginBottom: 20,
        },
        retryButton: {
          backgroundColor: "#FF9800",
          paddingHorizontal: 24,
          paddingVertical: 12,
          borderRadius: 8,
        },
        retryButtonText: {
          color: "#FFFFFF",
          fontSize: 16,
          fontWeight: "600",
        },
      });