import { StyleSheet, Platform } from "react-native";

export const COLORS = {
    primary: "#0E71C6",
    primaryLight: "#E7F2FD",
    primaryDark: "#0856A5",
    accent: "#FE486C",
    success: "#34C759",
    background: "#FFFFFF",
    card: "#FFFFFF",
    cardDark: "#F2F7FC",
    text: "#1A2D40",
    textSecondary: "#68788A",
    textLight: "#8E9CAA",
    border: "#E5ECF5",
    borderDark: "#CCD7E6",
    inactive: "#A9B7C7",
    unread: "#E7F2FD",
    unreadIndicator: "#0E71C6",
  };
  
export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    // Header
    header: {
      marginTop: 60,
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: COLORS.background,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    titleContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    titleConversations: {
      fontSize: 26,
      fontWeight: "700",
      color: COLORS.text,
      letterSpacing: -0.5,
    },
    badgeContainer: {
      backgroundColor: COLORS.primary,
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 8,
      paddingHorizontal: 6,
    },
    badgeText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "600",
    },
    archiveInfoContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 8,
    },
    archiveInfo: {
      color: COLORS.textSecondary,
      fontSize: 13,
      fontWeight: "500",
      marginLeft: 6,
    },
    actionButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: COLORS.primaryLight,
      justifyContent: "center",
      alignItems: "center",
      ...Platform.select({
        ios: {
          shadowColor: COLORS.primary,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 4,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    // Liste principale
    mainContent: {
      flex: 1,
    },
    conversationsList: {
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    conversationItem: {
      flexDirection: "row",
      padding: 16,
      borderRadius: 16,
      marginVertical: 8,
      backgroundColor: COLORS.card,
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
        },
        android: {
          elevation: 3,
        },
      }),
    },
    unreadConversation: {
      backgroundColor: COLORS.unread,
      borderLeftWidth: 4,
      borderLeftColor: COLORS.unreadIndicator,
    },
    avatarContainer: {
      position: "relative",
      marginRight: 16,
    },
    profilePhoto: {
      width: 56,
      height: 56,
      borderRadius: 28,
      borderWidth: 2,
      borderColor: COLORS.background,
    },
    defaultProfilePhoto: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: "#F0F4F8",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: COLORS.border,
    },
    unreadDefaultPhoto: {
      backgroundColor: COLORS.primaryLight,
      borderColor: COLORS.primaryLight,
    },
    avatarText: {
      fontSize: 22,
      fontWeight: "700",
      color: COLORS.textSecondary,
    },
    unreadBadge: {
      position: "absolute",
      bottom: -2,
      right: -2,
      backgroundColor: COLORS.accent,
      minWidth: 22,
      height: 22,
      borderRadius: 11,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: COLORS.background,
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.15,
          shadowRadius: 3,
        },
        android: {
          elevation: 3,
        },
      }),
    },
    unreadBadgeText: {
      color: "#fff",
      fontSize: 10,
      fontWeight: "700",
    },
    conversationDetails: {
      flex: 1,
      justifyContent: "center",
    },
    headingRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    conversationTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: COLORS.text,
      flex: 1,
      marginRight: 8,
    },
    unreadTitle: {
      fontWeight: "700",
      color: COLORS.primary,
    },
    timestamp: {
      fontSize: 12,
      color: COLORS.textLight,
      fontWeight: "500",
    },
    unreadTimestamp: {
      color: COLORS.primary,
      fontWeight: "600",
    },
    lastMessage: {
      fontSize: 14,
      color: COLORS.textSecondary,
      lineHeight: 20,
    },
    unreadText: {
      fontWeight: "500",
      color: COLORS.text,
    },
    // États de chargement et vide
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingBottom: 50,
    },
    loadingText: {
      fontSize: 16,
      color: COLORS.textSecondary,
      marginTop: 20,
      fontWeight: "500",
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 30,
      paddingBottom: 100,
    },
    emptyImageContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: COLORS.cardDark,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 24,
    },
    noConversation: {
      fontSize: 20,
      fontWeight: "700",
      color: COLORS.text,
      marginBottom: 12,
    },
    emptyDescription: {
      fontSize: 16,
      color: COLORS.textSecondary,
      textAlign: "center",
      lineHeight: 24,
      maxWidth: "80%",
    },
    // Section archivée
    hiddenPanel: {
      backgroundColor: COLORS.cardDark,
      borderRadius: 20,
      margin: 16,
      marginTop: 8,
      overflow: "hidden",
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: 0.1,
          shadowRadius: 6,
        },
        android: {
          elevation: 4,
        },
      }),
    },
    hiddenPanelHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    hiddenHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    hiddenHeaderIcon: {
      marginRight: 8,
    },
    hiddenPanelTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: COLORS.text,
    },
    badge: {
      backgroundColor: COLORS.primary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    badgeCount: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "700",
    },
    hiddenList: {
      maxHeight: 300,
    },
    hiddenListContent: {
      paddingVertical: 8,
    },
    hiddenConversationItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 16,
      marginHorizontal: 12,
      marginVertical: 6,
      backgroundColor: COLORS.card,
      borderRadius: 12,
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.05,
          shadowRadius: 2,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    hiddenUserInfo: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    hiddenProfilePhoto: {
      width: 46,
      height: 46,
      borderRadius: 23,
      marginRight: 14,
      borderWidth: 2,
      borderColor: COLORS.background,
    },
    hiddenDefaultPhoto: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: "#F0F4F8",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 14,
      borderWidth: 2,
      borderColor: COLORS.border,
    },
    hiddenAvatarText: {
      fontSize: 18,
      fontWeight: "700",
      color: COLORS.textSecondary,
    },
    hiddenConversationName: {
      fontSize: 16,
      fontWeight: "600",
      color: COLORS.text,
      flex: 1,
    },
    recoverButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.primary,
      borderRadius: 20,
      paddingHorizontal: 8,
      paddingVertical: 8,
      ...Platform.select({
        ios: {
          shadowColor: COLORS.primary,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.3,
          shadowRadius: 3,
        },
        android: {
          elevation: 3,
        },
      }),
    },
    recoverButtonText: {
      color: "white",
      fontSize: 14,
      fontWeight: "600",
      marginLeft: 6,
    },
    emptyArchiveContainer: {
      padding: 30,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyIconContainer: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: COLORS.cardDark,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    emptyArchiveTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: COLORS.text,
      marginBottom: 8,
    },
    emptyArchiveText: {
      fontSize: 14,
      color: COLORS.textSecondary,
      textAlign: "center",
      maxWidth: "80%",
      lineHeight: 20,
    },
    globalLoader: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: COLORS.background,
    },
  });