import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F5F5F5",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F5F5F5",
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: "#757575",
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 20,
    },
    header: {
      paddingTop: Platform.OS === "ios" ? 60 : 40,
      paddingBottom: 30,
      paddingHorizontal: 24,
      alignItems: "center",
    },
    headerIcon: {
      fontSize: 48,
      marginBottom: 12,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: "bold",
      color: "#FFFFFF",
      marginBottom: 8,
    },
    headerSubtitle: {
      fontSize: 14,
      color: "rgba(255,255,255,0.9)",
      textAlign: "center",
    },
    section: {
      backgroundColor: "#FFFFFF",
      marginHorizontal: 16,
      marginTop: 16,
      borderRadius: 16,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#212121",
    },
    addButton: {
      backgroundColor: "#43A047",
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
    },
    addButtonText: {
      color: "#FFFFFF",
      fontWeight: "600",
      fontSize: 14,
    },
    emptyState: {
      alignItems: "center",
      paddingVertical: 40,
    },
    emptyIcon: {
      fontSize: 64,
      marginBottom: 16,
    },
    emptyText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#212121",
      marginBottom: 8,
    },
    emptySubtext: {
      fontSize: 14,
      color: "#757575",
    },
    memberCard: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    // ✨ NOUVEAU STYLE : Pour la vraie photo
    memberAvatarImage: {
      width: 48,
      height: 48,
      borderRadius: 24,
      marginRight: 16,
    },
    // ✨ NOUVEAU STYLE : Cercle avec texte "Aucune photo disponible"
    memberAvatarNoPhoto: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#E0E0E0",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      padding: 4,
    },
    // ✨ NOUVEAU STYLE : Texte à l'intérieur du cercle
    memberAvatarNoPhotoText: {
      fontSize: 7,
      fontWeight: "600",
      color: "#757575",
      textAlign: "center",
      lineHeight: 9,
    },
    memberInfo: {
      flex: 1,
    },
    memberName: {
      fontSize: 16,
      fontWeight: "600",
      color: "#212121",
      marginBottom: 4,
    },
    memberRole: {
      fontSize: 14,
      color: "#757575",
    },
    memberActions: {
      flexDirection: "row",
      gap: 12,
    },
    actionButton: {
      fontSize: 20,
      padding: 4,
    },
    infoBox: {
      flexDirection: "row",
      backgroundColor: "#E8F5E9",
      marginHorizontal: 16,
      marginTop: 16,
      borderRadius: 12,
      padding: 16,
    },
    infoIcon: {
      fontSize: 24,
      marginRight: 12,
    },
    infoText: {
      flex: 1,
      fontSize: 14,
      color: "#2E7D32",
      lineHeight: 20,
    },
    actions: {
      flexDirection: "row",
      marginHorizontal: 16,
      marginTop: 24,
      gap: 12,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: "#E0E0E0",
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: "center",
    },
    cancelButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#424242",
    },
    saveButton: {
      flex: 1,
      backgroundColor: "#43A047",
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: "center",
    },
    saveButtonDisabled: {
      backgroundColor: "#A5D6A7",
    },
    saveButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#FFFFFF",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
    },
    modalScrollContent: {
      flexGrow: 1,
      justifyContent: "center",
      padding: 20,
    },
    modalContent: {
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      padding: 24,
      width: "100%",
      maxWidth: 500,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#212121",
      marginBottom: 20,
    },
    photoSection: {
      marginBottom: 20,
      alignItems: "center",
    },
    photoContainer: {
      alignItems: "center",
      width: "100%",
    },
    photoPreview: {
      width: 100,
      height: 100,
      borderRadius: 50,
      overflow: "hidden",
      marginBottom: 12,
      borderWidth: 2,
      borderColor: "#43A047",
    },
    photoImage: {
      width: "100%",
      height: "100%",
    },
    photoPlaceholder: {
      width: "100%",
      height: "100%",
      backgroundColor: "#F5F5F5",
      justifyContent: "center",
      alignItems: "center",
    },
    photoButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#43A047",
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      gap: 6,
    },
    photoButtonText: {
      fontSize: 12,
      fontWeight: "600",
      color: "#FFFFFF",
    },
    photoDeleteButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FFEBEE",
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginTop: 8,
      gap: 4,
    },
    photoDeleteButtonText: {
      fontSize: 12,
      fontWeight: "600",
      color: "#E53935",
    },
    modalInputGroup: {
      marginBottom: 16,
    },
    modalLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: "#424242",
      marginBottom: 8,
    },
    modalInput: {
      backgroundColor: "#F9FAFB",
      borderRadius: 12,
      padding: 16,
      fontSize: 16,
      color: "#212121",
      borderWidth: 1,
      borderColor: "#E5E7EB",
    },
    modalActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    modalCancelButton: {
      flex: 1,
      backgroundColor: "#E0E0E0",
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
    },
    modalCancelText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#424242",
    },
    modalSaveButton: {
      flex: 1,
      backgroundColor: "#43A047",
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
    },
    modalSaveText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#FFFFFF",
    },
  });