import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor: "#F5F5F5",
        },
        loadingContainer: {
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "#F5F5F5",
          padding: 20,
        },
        loadingText: {
          marginTop: 16,
          fontSize: 16,
          color: "#757575",
        },
        errorText: {
          fontSize: 18,
          fontWeight: "bold",
          color: "#E53935",
          textAlign: "center",
          marginTop: 16,
          marginHorizontal: 20,
        },
        errorSubtext: {
          fontSize: 14,
          color: "#757575",
          textAlign: "center",
          marginTop: 8,
          marginHorizontal: 20,
        },
        scrollView: {
          flex: 1,
        },
        scrollContent: {
          paddingBottom: 20,
        },
        header: {
          paddingTop: Platform.OS === "ios" ? 60 : 40,
          paddingBottom: 30,
          paddingHorizontal: 24,
          alignItems: "center",
        },
        headerIcon: {
          fontSize: 48,
          marginBottom: 12,
        },
        headerTitle: {
          fontSize: 26,
          fontWeight: "bold",
          color: "#FFFFFF",
          marginBottom: 8,
        },
        headerSubtitle: {
          fontSize: 14,
          color: "rgba(255,255,255,0.9)",
          textAlign: "center",
        },
        section: {
          backgroundColor: "#FFFFFF",
          marginHorizontal: 16,
          marginTop: 16,
          borderRadius: 16,
          padding: 20,
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 8,
          elevation: 4,
        },
        sectionTitle: {
          fontSize: 18,
          fontWeight: "bold",
          color: "#212121",
          marginBottom: 20,
        },
        photoSection: {
          marginBottom: 20,
        },
        photoContainer: {
          alignItems: "center",
        },
        photoPreview: {
          width: 150,
          height: 150,
          borderRadius: 75,
          overflow: "hidden",
          marginBottom: 16,
          borderWidth: 3,
          borderColor: "#43A047",
        },
        photoImage: {
          width: "100%",
          height: "100%",
        },
        photoPlaceholder: {
          width: "100%",
          height: "100%",
          backgroundColor: "#F5F5F5",
          justifyContent: "center",
          alignItems: "center",
        },
        photoPlaceholderText: {
          fontSize: 12,
          color: "#BDBDBD",
          marginTop: 8,
        },
        photoButton: {
          flexDirection: "row",
          alignItems: "center",
          backgroundColor: "#43A047",
          paddingVertical: 12,
          paddingHorizontal: 24,
          borderRadius: 12,
          gap: 8,
        },
        photoButtonText: {
          fontSize: 14,
          fontWeight: "600",
          color: "#FFFFFF",
        },
        photoDeleteButton: {
          flexDirection: "row",
          alignItems: "center",
          backgroundColor: "#FFEBEE",
          paddingVertical: 10,
          paddingHorizontal: 20,
          borderRadius: 12,
          marginTop: 12,
          gap: 8,
        },
        photoDeleteButtonText: {
          fontSize: 14,
          fontWeight: "600",
          color: "#E53935",
        },
        inputGroup: {
          marginBottom: 20,
        },
        label: {
          fontSize: 14,
          fontWeight: "600",
          color: "#424242",
          marginBottom: 8,
        },
        input: {
          backgroundColor: "#F9FAFB",
          borderRadius: 12,
          padding: 16,
          fontSize: 16,
          color: "#212121",
          borderWidth: 1,
          borderColor: "#E5E7EB",
        },
        multilineInput: {
          minHeight: 100,
          textAlignVertical: "top",
        },
        infoBox: {
          flexDirection: "row",
          backgroundColor: "#E8F5E9",
          marginHorizontal: 16,
          marginTop: 16,
          borderRadius: 12,
          padding: 16,
        },
        infoIcon: {
          fontSize: 24,
          marginRight: 12,
        },
        infoText: {
          flex: 1,
          fontSize: 14,
          color: "#2E7D32",
          lineHeight: 20,
        },
        actions: {
          flexDirection: "row",
          marginHorizontal: 16,
          marginTop: 24,
          gap: 12,
        },
        cancelButton: {
          flex: 1,
          backgroundColor: "#E0E0E0",
          borderRadius: 12,
          paddingVertical: 16,
          alignItems: "center",
        },
        cancelButtonText: {
          fontSize: 16,
          fontWeight: "600",
          color: "#424242",
        },
        saveButton: {
          flex: 1,
          backgroundColor: "#43A047",
          borderRadius: 12,
          paddingVertical: 16,
          alignItems: "center",
        },
        saveButtonDisabled: {
          backgroundColor: "#A5D6A7",
        },
        saveButtonText: {
          fontSize: 16,
          fontWeight: "600",
          color: "#FFFFFF",
        },
      });