import { StyleSheet, Platform, Dimensions } from "react-native";

const COLORS = {
  primary: "#062C41",
  secondary: "#FF9800",
  accent: "#5D7FDB",
  danger: "#f44336",
  success: "#4CAF50",
  background: "#F8F9FA",
  card: "#FFFFFF",
  cardDark: "#052436",
  border: "#E0E0E0",
  gradient: {
    primary: ["#062C41", "#0A4D6E"] as readonly [string, string],
    secondary: ["#FF9800", "#FFB547"] as readonly [string, string],
    success: ["#4CAF50", "#66BB6A"] as readonly [string, string],
    danger: ["#f44336", "#EF5350"] as readonly [string, string],
    disabled: ["#9E9E9E", "#BDBDBD"] as readonly [string, string],
  },
  text: {
    primary: "#333333",
    secondary: "#666666",
    light: "#FFFFFF",
    muted: "#999999",
    accent: "#5D7FDB",
  },
};
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 16,
    color: COLORS.text.secondary,
    fontSize: 16,
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    zIndex: 10,
  },
  imageContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 5,
    overflow: "hidden",
  },
  imageBackground: {
    width: Dimensions.get("window").width,
    height: "100%",
  },
  imageGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  navigationBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: Platform.OS === "ios" ? 60 : 40,
    paddingHorizontal: 20,
    zIndex: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    marginRight: 10,
  },
  headerActions: {
    flexDirection: "row",
  },
  headerActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    marginLeft: 10,
  },
  paginationContainer: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    bottom: 16,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: COLORS.secondary,
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  scrollContent: {
    backgroundColor: COLORS.background,
  },
  mainContent: {
    paddingHorizontal: 20,
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: -20,
  },
  titleContainer: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.text.primary,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  organizerInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  organizedBy: {
    fontSize: 14,
    color: COLORS.text.secondary,
    marginRight: 8,
  },
  organizerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.background,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  organizerPhoto: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 8,
  },
  organizerName: {
    fontSize: 14,
    fontWeight: "500",
    color: COLORS.text.primary,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    marginBottom: 10,
  },
  locationButton: {
    flex: 1,
    marginRight: 10,
    borderRadius: 12,
    overflow: "hidden",
    height: 48,
  },
  registerButton: {
    borderRadius: 12,
    overflow: "hidden",
    height: 48,
  },
  unregisterButton: {
    borderRadius: 12,
    overflow: "hidden",
    height: 48,
  },
  organizerOnlyButton: {
    borderRadius: 12,
    overflow: "hidden",
    height: 48,
  },
  buttonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    paddingHorizontal: 16,
  },
  actionButtonText: {
    color: COLORS.text.light,
    fontWeight: "600",
    marginLeft: 8,
    fontSize: 15,
  },
  detailsCard: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 3,
  },
  detailRow: {
    flexDirection: "row",
    marginBottom: 16,
    alignItems: "flex-start",
  },
  detailIconContainer: {
    width: 40,
    alignItems: "center",
    marginRight: 12,
  },
  detailTextContainer: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 14,
    color: COLORS.text.secondary,
    marginBottom: 2,
  },
  detailText: {
    fontSize: 16,
    color: COLORS.text.primary,
    lineHeight: 22,
  },
  descriptionCard: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 3,
  },
  descriptionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text.primary,
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 15,
    color: COLORS.text.secondary,
    lineHeight: 22,
  },
  participantsCard: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 3,
  },
  participantsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  participantsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text.primary,
  },
  participantsCountBadge: {
    backgroundColor: COLORS.accent,
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 10,
  },
  participantsCount: {
    color: COLORS.text.light,
    fontSize: 14,
    fontWeight: "600",
  },
  participantsList: {
    width: "100%",
  },
  participantItem: {
    flex: 1,
    alignItems: "center",
    marginBottom: 16,
    maxWidth: "33.33%",
  },
  organizerParticipantItem: {},
  participantImageContainer: {
    position: "relative",
    marginBottom: 8,
  },
  participantImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  organizerBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.secondary,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fff",
  },
  participantName: {
    fontSize: 12,
    color: COLORS.text.primary,
    textAlign: "center",
    fontWeight: "500",
    width: "80%",
  },
  noParticipantsContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 30,
  },
  noParticipantsText: {
    textAlign: "center",
    color: COLORS.text.muted,
    marginTop: 16,
    fontSize: 14,
  },
  floatingButtonContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
    zIndex: 5,
  },
  floatingButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  floatingButtonGradient: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
});
