import { StyleSheet, Platform, StatusBar} from "react-native";

const COLORS = {
    primary: "#1B5D85",
    secondary: "#1B5D85",
    danger: "#f44336",
    success: "#4CAF50",
    background: "#F8F9FA",
    card: "#FFFFFF",
    border: "#E0E0E0",
    text: {
      primary: "#333333",
      secondary: "#666666",
      light: "#FFFFFF",
      muted: "#999999",
    },
  };

  const LAYOUT = {
    radius: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 24,
      circle: 9999,
    },
    header: {
      height: Platform.OS === "ios" ? 100 : 90,
      padding: Platform.OS === "ios" ? 50 : 30,
    },
    tabBar: {
      height: 64 + (Platform.OS === "ios" ? 20 : 0),
      buttonSize: 44,
    },
    statusBar: {
      height: StatusBar.currentHeight || (Platform.OS === "ios" ? 44 : 24),
    },
    border: {
      width: 1,
      color: "rgba(0,0,0,0.08)",
    },
    shadow: {
      small: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
      },
      medium: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 4,
      },
      large: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.16,
        shadowRadius: 12,
        elevation: 8,
      },
    },
  };
  
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  // ✅ Header styles - CONSERVÉS
  header: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Platform.OS === "ios" ? 45 : 45,
    paddingBottom: 20,
    paddingHorizontal: 20,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  headerIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
  badge: {
    position: "absolute",
    top: -6,
    right: -6,
    backgroundColor: COLORS.danger,
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "bold",
  },
  // 🆕 Nouveaux styles modernes
  scrollContent: {
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  introSection: {
    marginBottom: 28,
  },
  introTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  introSubtitle: {
    fontSize: 15,
    color: "#64748B",
    lineHeight: 22,
  },
  cardWrapper: {
    marginBottom: 16,
  },
  modernCard: {
    borderRadius: 16,
    overflow: "hidden",
  },
  cardGradientBorder: {
    padding: 2,
    borderRadius: 16,
  },
  cardInner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 16,
  },
  cardIconContainer: {
    marginRight: 16,
  },
  cardIconGradient: {
    width: 56,
    height: 56,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  cardContent: {
    flex: 1,
    marginRight: 12,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#1E293B",
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  cardDescription: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 20,
  },
  cardArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  ctaButtonContainer: {
    marginTop: 32,
    marginBottom: 24,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#8E2DE2",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  ctaButton: {
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
    position: "relative",
    overflow: "hidden",
  },
  ctaContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  ctaButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 12,
    letterSpacing: 0.5,
  },
  ctaShine: {
    position: "absolute",
    top: 0,
    left: -100,
    width: 100,
    height: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    transform: [{ skewX: "-20deg" }],
  },
  emergencySection: {
    backgroundColor: "#FEF2F2",
    borderRadius: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: "#FEE2E2",
    alignItems: "center",
  },
  emergencyTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#991B1B",
    marginBottom: 12,
  },
  emergencyButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  emergencyText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#EF4444",
    marginLeft: 8,
  },
});

    