import { StyleSheet, Platform, Dimensions,StatusBar } from "react-native";
// Obtenir dimensions de l'écran pour le responsive
const { width, height } = Dimensions.get("window");
const isIOS = Platform.OS === "ios";
const statusBarHeight = StatusBar.currentHeight || 0;

const LAYOUT = {
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    circle: 9999,
  },
  header: {
    height: Platform.OS === "ios" ? 100 : 90,
    padding: Platform.OS === "ios" ? 50 : 30,
  },
  tabBar: {
    height: 64 + (Platform.OS === "ios" ? 20 : 0),
    buttonSize: 44,
  },
  statusBar: {
    height: StatusBar.currentHeight || (Platform.OS === "ios" ? 44 : 24),
  },
  border: {
    width: 1,
    color: "rgba(0,0,0,0.08)",
  },
  shadow: {
    small: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.16,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};

const safeTop = isIOS ? 44 : statusBarHeight;
export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#FFFFFF",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#1B5D85",
      paddingTop: safeTop,
      paddingBottom: 12,
      paddingHorizontal: 16,
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    },
    headerButton: {
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 20,
    },
    headerIconButton: {
      width: 38,
      height: 38,
      borderRadius: LAYOUT.radius.circle,
      justifyContent: "center",
      alignItems: "center",
  
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.15)",
    },
    typeBadge: {
      flexDirection: "row",
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: "#FFFFFF",
      letterSpacing: 0.5,
    },
    contentContainer: {
      flex: 1,
    },
    subHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: "#F9FAFC",
      borderBottomWidth: 1,
      borderBottomColor: "#E5E7EB",
    },
    filterButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F0F7FF",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    filterButtonText: {
      marginLeft: 4,
      color: "#4A90E2",
      fontWeight: "600",
      fontSize: 14,
    },
    markAllButtonMini: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F0F7FF",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    markAllButtonTextMini: {
      marginLeft: 4,
      color: "#4A90E2",
      fontWeight: "600",
      fontSize: 14,
    },
    iconStyle: {
      marginRight: 4,
    },
    badge: {
      position: "absolute",
      top: -4,
      right: -4,
      backgroundColor: "#FF5252",
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 4,
      borderWidth: 1.5,
      borderColor: "#FFFFFF",
    },
    badgeText: {
      color: "#FFFFFF",
      fontSize: 10,
      fontWeight: "700",
    },
    loadingContainer: {
      flex: 1,
      backgroundColor: "#FFFFFF",
    },
    loadingContent: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: "#64748B",
      fontWeight: "500",
    },
    flatListContent: {
      flexGrow: 1,
      paddingVertical: 8,
    },
    notificationItem: {
      backgroundColor: "#FFFFFF",
      paddingVertical: 16,
      paddingHorizontal: 16,
      marginHorizontal: 12,
      marginVertical: 6,
      borderRadius: 12,
      elevation: 1,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    },
    unreadNotification: {
      backgroundColor: "#F0F7FF",
    },
    unreadIndicator: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: 4,
      backgroundColor: "#4A90E2",
      borderTopLeftRadius: 12,
      borderBottomLeftRadius: 12,
    },
    notificationContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    profilePhotoContainer: {
      position: "relative",
      marginRight: 12,
    },
    profilePhoto: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: "#F3F4F6",
    },
    notificationTypeIcon: {
      position: "absolute",
      bottom: 0,
      right: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: "#4A90E2",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#FFFFFF",
    },
    notificationTextContainer: {
      flex: 1,
      justifyContent: "center",
    },
    notificationMessage: {
      fontSize: 14,
      color: "#1F2937",
      marginBottom: 4,
      lineHeight: 20,
    },
    notificationDate: {
      fontSize: 12,
      color: "#6B7280",
    },
    chevronIcon: {
      marginLeft: 8,
    },
    markAsReadButton: {
      backgroundColor: "#4A90E2",
      justifyContent: "center",
      alignItems: "center",
      width: 100,
      height: "87%",
      marginVertical: 6,
      marginLeft: 12,
      borderRadius: 12,
    },
    markAsReadText: {
      color: "#FFFFFF",
      fontWeight: "600",
      marginTop: 4,
    },
    deleteButton: {
      backgroundColor: "#FF5252",
      justifyContent: "center",
      alignItems: "center",
      width: 100,
      height: "87%",
      marginVertical: 6,
      marginRight: 12,
      borderRadius: 12,
    },
    deleteButtonText: {
      color: "#FFFFFF",
      fontWeight: "600",
      marginTop: 4,
    },
    emptyContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 32,
      marginTop: height * 0.1,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: "#374151",
      marginTop: 16,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 14,
      color: "#6B7280",
      textAlign: "center",
      lineHeight: 20,
    },
    markAllButtonContainer: {
      position: "absolute",
      bottom: 24,
      left: 0,
      right: 0,
      alignItems: "center",
      paddingHorizontal: 16,
    },
    markAllButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#4A90E2",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      elevation: 4,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
    },
    markAllButtonText: {
      color: "#FFFFFF",
      fontWeight: "600",
      fontSize: 15,
      marginLeft: 8,
    },
  
    // Modal styles
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingBottom: 84,
    },
    modalContainer: {
      width: width * 0.92,
      maxWidth: 450,
      maxHeight: height * 0.95,
      backgroundColor: "#FFFFFF",
      borderRadius: 20,
      overflow: "hidden",
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
    },
    modalHeader: {
      borderBottomWidth: 1,
      borderBottomColor: "#EEEEEE",
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
    },
    modalHeaderContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: "#111827",
      letterSpacing: -0.25,
    },
    modalSubtitle: {
      fontSize: 14,
      color: "#6B7280",
      marginTop: 4,
    },
    modalCloseButton: {
      padding: 6,
      borderRadius: 20,
      backgroundColor: "#F5F5F5",
    },
    modalScrollView: {
      maxHeight: Math.min(550, height * 0.5),
    },
    modalScrollContent: {
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: "#EEEEEE",
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    categorySection: {
      marginBottom: 24,
    },
    categoryDivider: {
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: "#F0F0F0",
      marginTop: 8,
    },
    categoryTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: "#111827",
      marginBottom: 12,
      letterSpacing: -0.25,
    },
    preferenceItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: "#F5F5F7",
    },
    preferenceTextContainer: {
      flex: 1,
      paddingRight: 16,
    },
    preferenceLabel: {
      fontSize: 15,
      color: "#333333",
      lineHeight: 20,
    },
    preferenceSwitch: {
      transform: [{ scaleX: 0.9 }, { scaleY: 0.9 }],
    },
    cancelButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginRight: 12,
      borderWidth: 1,
      borderColor: "#E5E7EB",
    },
    cancelButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: "#4B5563",
    },
    saveButton: {
      backgroundColor: "#4A90E2",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      elevation: 1,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    saveButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: "#FFFFFF",
    },
  });