import { StyleSheet, Dimensions} from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
      },
      background: {
        flex: 1,
        width: '100%',
        height: '100%',
      },
      backgroundImage: {
        resizeMode: 'cover',
      },
      gradientOverlay: {
        ...StyleSheet.absoluteFillObject,
      },
      scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingVertical: 40,
      },
      blurContainer: {
        borderRadius: 24,
        overflow: 'hidden',
        padding: 24,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
      },
      stepContainer: {
        width: '100%',
      },
      progressContainer: {
        marginBottom: 24,
      },
      progressBar: {
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 3,
        overflow: 'hidden',
        marginBottom: 8,
      },
      progressIndicator: {
        height: '100%',
        backgroundColor: '#6366f1',
        borderRadius: 3,
      },
      progressText: {
        color: '#cbd5e1',
        fontSize: 13,
        textAlign: 'center',
        fontWeight: '500',
      },
      stepTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#ffffff',
        marginBottom: 8,
        textAlign: 'center',
      },
      stepDescription: {
        fontSize: 15,
        color: '#94a3b8',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
      },
      formContainer: {
        gap: 16,
        marginBottom: 24,
      },
      inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.12)',
      },
      inputIcon: {
        marginRight: 12,
      },
      input: {
        flex: 1,
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '500',
      },
      verificationIndicator: {
        marginLeft: 8,
      },
      passwordToggle: {
        padding: 4,
      },
      errorText: {
        color: '#fca5a5',
        fontSize: 12,
        marginTop: 6,
        marginLeft: 4,
      },
      successText: {
        color: '#6ee7b7',
        fontSize: 12,
        marginTop: 6,
        marginLeft: 4,
      },
      municipalityRecapBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        padding: 16,
        borderRadius: 12,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.3)',
      },
      municipalityRecapText: {
        flex: 1,
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
      },
      // ✅ NOUVEAU STYLE pour le message d'avertissement
      warningBox: {
        flexDirection: 'row',
        backgroundColor: '#fffbeb',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#fbbf24',
        gap: 12,
      },
      warningBoxText: {
        flex: 1,
        fontSize: 13,
        color: '#92400e',
        lineHeight: 18,
      },
      passwordRulesContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderRadius: 12,
        padding: 16,
        gap: 8,
      },
      passwordRulesTitle: {
        fontSize: 13,
        color: '#cbd5e1',
        marginBottom: 4,
        fontWeight: '600',
      },
      passwordRuleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
      },
      passwordRuleText: {
        fontSize: 13,
        color: '#94a3b8',
      },
      passwordRuleTextValid: {
        color: '#6ee7b7',
      },
      sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 8,
      },
      photoManagerContainer: {
        alignItems: 'center',
        marginBottom: 16,
      },
      photoHelperText: {
        fontSize: 12,
        color: '#94a3b8',
        marginTop: 8,
        textAlign: 'center',
      },
      searchContainer: {
        gap: 12,
      },
      searchButtonContainer: {
        width: '100%',
      },
      searchButton: {
        borderRadius: 14,
        overflow: 'hidden',
      },
      searchButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        gap: 8,
      },
      searchButtonText: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '600',
      },
      selectedLocationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        padding: 12,
        borderRadius: 12,
        gap: 8,
        marginTop: 12,
      },
      selectedLocationText: {
        flex: 1,
        color: '#6ee7b7',
        fontSize: 14,
        fontWeight: '500',
      },
      navigationButtons: {
        flexDirection: 'row',
        gap: 12,
      },
      backButton: {
        flex: 0.35,
        borderRadius: 14,
        overflow: 'hidden',
        height: 50,
      },
      nextButtonMain: {
        flex: 0.65,
        borderRadius: 14,
        overflow: 'hidden',
        height: 50,
      },
      registerButton: {
        flex: 0.65,
        borderRadius: 14,
        overflow: 'hidden',
        height: 50,
      },
      nextButton: {
        width: '100%',
        borderRadius: 14,
        overflow: 'hidden',
        height: 50,
      },
      buttonGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        gap: 8,
      },
      gradientButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        gap: 8,
      },
      backButtonText: {
        color: '#cbd5e1',
        fontSize: 15,
        fontWeight: '600',
      },
      nextButtonText: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '600',
      },
      registerButtonText: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '600',
      },
      buttonDisabled: {
        opacity: 0.5,
      },
      loginLink: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 24,
        gap: 8,
      },
      loginText: {
        color: '#94a3b8',
        fontSize: 14,
      },
      loginButton: {
        paddingHorizontal: 4,
      },
      loginButtonText: {
        color: '#6366f1',
        fontSize: 14,
        fontWeight: '600',
      },
      accountTypeContainer: {
        flexDirection: 'column',
        gap: 16,
        marginTop: 24,
        marginBottom: 24,
      },
      accountTypeCard: {
        borderRadius: 16,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
      },
      accountTypeCardSelected: {
        elevation: 8,
        shadowOpacity: 0.25,
        shadowRadius: 12,
      },
      accountTypeGradient: {
        padding: 24,
        alignItems: 'center',
        minHeight: 180,
        justifyContent: 'center',
      },
      accountTypeTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1e293b',
        marginTop: 12,
        marginBottom: 8,
      },
      accountTypeTitleSelected: {
        color: '#ffffff',
      },
      accountTypeDescription: {
        fontSize: 14,
        color: '#64748b',
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 16,
      },
      accountTypeDescriptionSelected: {
        color: '#e0e7ff',
      },
      validationBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginTop: 12,
      },
      validationBadgeText: {
        fontSize: 12,
        color: '#10b981',
        marginLeft: 6,
        fontWeight: '600',
      },
      infoBox: {
        flexDirection: 'row',
        backgroundColor: '#eff6ff',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#6366f1',
        marginTop: 16,
        gap: 12,
      },
      infoBoxText: {
        flex: 1,
        fontSize: 13,
        color: '#1e40af',
        lineHeight: 18,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        padding: 20,
      },
      modalContent: {
        backgroundColor: '#1e293b',
        borderRadius: 20,
        maxHeight: height * 0.7,
        overflow: 'hidden',
      },
      modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
      },
      modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
      },
      suggestionsList: {
        maxHeight: height * 0.5,
      },
      suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.05)',
        gap: 12,
      },
      suggestionIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      suggestionTextContainer: {
        flex: 1,
      },
      suggestionCityName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 2,
      },
      suggestionPostalCode: {
        fontSize: 13,
        color: '#94a3b8',
      },
      noResultsText: {
        padding: 40,
        textAlign: 'center',
        color: '#94a3b8',
        fontSize: 14,
      },
    });
    
    