import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F5F5F5",
    },
    header: {
      paddingBottom: 20,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
    headerContent: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 10,
    },
    menuButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: "#FFFFFF",
      letterSpacing: 0.5,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      alignItems: "center",
      justifyContent: "center",
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
    },
    statsCard: {
      borderRadius: 16,
      padding: 20,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: "rgba(142, 45, 226, 0.2)",
    },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-around",
    },
    statItem: {
      alignItems: "center",
    },
    statValue: {
      fontSize: 24,
      fontWeight: "700",
      color: "#0A0A0A",
      marginTop: 8,
    },
    statLabel: {
      fontSize: 12,
      color: "#737373",
      marginTop: 4,
    },
    voteCard: {
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
      position: "relative",
    },
    voteBadge: {
      position: "absolute",
      top: 16,
      right: 16,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    voteBadgeUp: {
      backgroundColor: "#10B981",
    },
    voteBadgeDown: {
      backgroundColor: "#EF4444",
    },
    voteBadgeText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "700",
      marginLeft: 6,
    },
    voteHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    voteHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    voteDate: {
      fontSize: 12,
      color: "#737373",
      marginLeft: 6,
    },
    reportInfo: {
      backgroundColor: "rgba(142, 45, 226, 0.05)",
      padding: 12,
      borderRadius: 12,
      marginTop: 8,
      borderLeftWidth: 3,
      borderLeftColor: "#8E2DE2",
    },
    reportHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    reportTypeBadge: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    reportTypeText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "600",
      marginLeft: 6,
    },
    reportTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: "#0A0A0A",
      marginBottom: 6,
    },
    reportDescription: {
      fontSize: 13,
      color: "#262626",
      lineHeight: 18,
      marginBottom: 12,
    },
    reportPhoto: {
      width: "100%",
      height: 150,
      borderRadius: 12,
      marginBottom: 12,
    },
    reportStats: {
      flexDirection: "row",
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: "rgba(0, 0, 0, 0.1)",
    },
    reportStatItem: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: 16,
    },
    reportStatText: {
      fontSize: 13,
      color: "#737373",
      marginLeft: 6,
      fontWeight: "600",
    },
    viewReportButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      paddingTop: 12,
    },
    viewReportText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#8E2DE2",
      marginRight: 6,
    },
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 60,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: "#0A0A0A",
      marginTop: 16,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 14,
      color: "#737373",
      textAlign: "center",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F5F5F5",
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: "#737373",
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F5F5F5",
      padding: 20,
    },
    errorTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#F44336",
      marginTop: 16,
      marginBottom: 8,
    },
    errorText: {
      fontSize: 14,
      color: "#737373",
      textAlign: "center",
      marginBottom: 20,
    },
    retryButton: {
      backgroundColor: "#8E2DE2",
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
    },
    retryButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
    },
  });