import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#F2F4F7",
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,  
    paddingTop: 50,
  },
  homeTitle: {
    flexDirection: "row",  
    alignItems: "center",  
  },
  backButton: {
    padding: 10,
    borderRadius: 90,
    alignSelf: "flex-start",
    backgroundColor: "#E0E0E0",
    marginLeft: 5,
    marginRight: 26,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#2c3e50",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2c3e50",
    textAlign: "center",
  },
  label: {
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
    fontSize: 14,
  },
  labelDescription: {
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
    fontSize: 14,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 12,
    borderRadius: 30,
    marginBottom: 20,
    backgroundColor: "#fff",
    fontSize: 16,
    color: "#333",
  },
  inputDescription: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    height: 100,
    padding: 12,
    borderRadius: 30,
    marginBottom: 20,
    backgroundColor: "#fff",
    fontSize: 16,
    color: "#333",
  },
  inputWithButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,  
  },
  inputSearch: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 12,
    borderRadius: 30,
    fontSize: 16,
    color: "#333",
    backgroundColor: "#fff",
  },
  searchButton: {
    padding: 12,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#2c3e50",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  locationButton: {
    padding: 12,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FF5733",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",  
    alignItems: "center",  
    backgroundColor: "rgba(0, 0, 0, 0.5)",  
  },
  modalContent: {
    width: "80%",  
    backgroundColor: "#fff",  
    borderRadius: 10,  
    padding: 20,  
    shadowColor: "#000",  
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.3,  
    shadowRadius: 5,  
    elevation: 10,  
    alignItems: "center",  
  },
  modalText: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 15,  
    textAlign: "center",  
    color: "#333",  
  },
  modalPercentage: {
    fontSize: 14,
    fontWeight: "500",
    marginTop: 10,  
    textAlign: "center",
    color: "#2c3e50",  
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  suggestionText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#333",
  },
  containerDate: {
    backgroundColor: "#fff",
    borderRadius: 30,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  selectedDate: {
    marginVertical: 15,
    fontSize: 18,
    color: "#555",
    fontWeight: "bold",
  },
  mapContainer: {
    marginVertical: 20,
    height: 400,
    borderRadius: 30,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  modal: {
    padding: 20,
    backgroundColor: "#fff",
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  activityIndicator: {
    marginTop: 20,
  },
  submitButtonContainer: {
    paddingBottom: 50,
    justifyContent: "center", 
    alignItems: "center", 
  },
  submitButton: {
    marginVertical: 20,  
    alignItems: "center",  
  },
  button: {
    backgroundColor: "#2c3e50",  
    paddingVertical: 15,  
    paddingHorizontal: 30,  
    borderRadius: 30, 
  },
  buttonText: {
    color: "#fff",  
    fontSize: 16,  
    fontWeight: "bold", 
    textAlign: "center", 
  },
  buttonPhoto: {
    width: "70%",
    height: 50,
    borderRadius: 25, 
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 25,
    backgroundColor: "#11998e",
    shadowColor: "#11998e",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
 
  buttonTextPhoto: {
    color: "#FFFFFF",  
    fontSize: 16,
    fontWeight: "bold",
    textTransform: "uppercase",  
    letterSpacing: 1,  
  },
  buttonDisabled: {
    backgroundColor: "#ccc",  
  },
  containerPhoto: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  photoContainer: {
    marginTop: 20,
    marginBottom: 20,
  },

  photoWrapper: {
    position: "relative", 
    marginRight: 10,
  },
  photo: {
    width: 100,
    height: 100,
    borderRadius: 5,
  },
  deleteButton: {
    position: "absolute",
    top: 5,
    right: 5,
    zIndex: 1,  
  },
  progressModalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
    width: 300,
  },
  
});
