import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    width: "100%",
  },
  dropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: "100%",
    maxWidth: "95%",
    padding: 15,
    borderRadius: 30,
    backgroundColor: "#f5f5f5",
  },
  dropdownText: {
    width: "85%",
    fontSize: 14,
    color: "#c7c7c7",
    paddingLeft: 10,
  },
  selectedCategory: {
    color: "#666",
  },
  boldText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#34495E",
  },
  modalOverlayCategorie: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContentCategorie: {
    width: "95%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    maxHeight: "80%",
  },
  categoriesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    padding: 10,
    gap: 20,
  },
  card: {
    backgroundColor: "#F2F4F7",
    borderRadius: 190,
    width: 300,
    padding: 40,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  expandedCard: {
    backgroundColor: "#e0f7ff",
    borderWidth: 1,
    borderColor: "#34495E",
  },
  cardTitle: {
    marginTop: 10,
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  cardDescription: {
    marginTop: 10,
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  lastCard: {
    marginBottom: 50,
  },
  closeButton: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#34495E",
    borderRadius: 30,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "95%",
    alignSelf: "center",
  },
  rowButtonMap: {
    width: "47%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#34495E",
    padding: 10,
    borderRadius: 50,
  },
  rowButtonLocation: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#EDAE49",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
    marginTop: 40,
  },
  selectedIconContainer: {
    alignItems: "center",
    paddingBottom: 10,
  },
  iconLabel: {
    marginTop: 5,
    fontSize: 12,
    color: "#34495E",
    fontWeight: "bold",
  },
  selectedIconLabel: {
    color: "#34495E",
    fontWeight: "bold",
  },
  containerSubmit: {
    alignItems: "center",
  },
  submitButtonContainer: {
    paddingBottom: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButton: {
    marginVertical: 20,
    alignItems: "center",
  },
  button: {
    backgroundColor: "#2c3e50",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
  },
  buttonSubmit: {
    backgroundColor: "#d81b60",
    shadowColor: "#d81b60",
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: "#333",
  },
  description: {
    marginTop: 10,
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34495E",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
    marginVertical: 10,
  },
  buttonMap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34495E",
    height: 80,
    borderRadius: 5,
    marginVertical: 10,
  },
  mapButtonText: {
    color: "white",
    marginLeft: 10,
  },
  closeButtonMap: {
    width: "100%",
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 10,
    borderRadius: 5,
  },
  closeButtonTextMap: {
    color: "white",
    fontWeight: "bold",
    fontSize: 25,
  },
  containerSecond: {
    flex: 1,
    paddingHorizontal: 20,
    marginTop: 35,
  },
  containerInput: {
    flex: 1,
  },

  title: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 15,
    marginTop: 35,
    color: "#333",
    textAlign: "center",
  },
  titlePhoto: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 35,
    color: "#333",
    textAlign: "center",
  },
  inputTitle: {
    flex: 1,
    width: 330,
    height: 50,
    maxHeight: 50,
    backgroundColor: "#f5f5f5",
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingLeft: 30,
    marginBottom: 25,
    fontSize: 16,
    color: "#333",
    overflow: "hidden",
  },
  input: {
    flex: 1,
    maxHeight: 250,
    backgroundColor: "#f5f5f5",
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 15,
    paddingLeft: 25,
    paddingTop: 20,
    fontSize: 16,
    color: "#333",
    overflow: "hidden",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  inputWithButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  inputSearch: {
    height: 50,
    textAlignVertical: "center",
    paddingHorizontal: 10,
    paddingLeft: 20,
    backgroundColor: "#f5f5f5",
    width: "65%",
    borderRadius: 30,  
    fontSize: 16,  
    color: "#333",
    marginTop: 40,
  },
  searchButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#34495E",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10, 
    marginTop: 40,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",  
    alignItems: "center",  
    backgroundColor: "rgba(0, 0, 0, 0.5)",  
  },
  modalContent: {
    width: "80%", 
    backgroundColor: "#fff",  
    borderRadius: 10, 
    padding: 20,  
    shadowColor: "#000",  
    shadowOffset: { width: 0, height: 4 },  
    shadowOpacity: 0.3, 
    shadowRadius: 5,  
    elevation: 10, 
    alignItems: "center",  
  },
  suggestionItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  suggestionText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#333",
  },
  closeModalButton: {
    marginTop: 10,
    alignSelf: "center",
    backgroundColor: "#34495E",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
  },
  closeModalButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  navigation: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  navButtonLeft: {
    position: "absolute",
    right: 110,
    bottom: 10,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 5,
  },

  navButtonRight: {
    position: "absolute",
    left: 110,
    bottom: 10,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 5,
  },
  homeTitle: {
    flexDirection: "row",  
    alignItems: "center",  
    marginBottom: 20,  
    marginTop: 10,
  },
  backButton: {
    padding: 10,
    borderRadius: 90,
    alignSelf: "flex-start",
    backgroundColor: "#E0E0E0",
    marginBottom: 20,
    marginTop: 40,
    marginLeft: 15,
    marginRight: 35,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#2c3e50",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2c3e50", 
    marginTop: 20,
    textAlign: "center",
  },
  containerThird: {
    paddingHorizontal: 20,
    marginTop: 35,
  },
});
