import { StyleSheet } from "react-native";

export default StyleSheet.create({

  cardContent: {
    flexDirection: "row",
    justifyContent: "space-around",  
    alignItems: "center",
    flexWrap: "wrap",  

  },
  statItem: {
    justifyContent: "center",  
    alignItems: "center",  
    padding: 10,  
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",  
    marginBottom: 5,  
    color: "#062C41",  
  },
  statLabel: {
    textAlign: "center",  
    fontSize: 14,
    color: "#555",  
    fontWeight: "bold",  
    lineHeight: 20,  
  },


  editButton: {
    marginTop: 10,
    marginHorizontal: 20,
    padding: 10,
    backgroundColor: "#062C41",
    borderRadius: 30,
    alignItems: "center",
  },
  editButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  editContainer: {
    marginTop: 20,
    padding: 20,
    borderRadius: 35,
    backgroundColor: "#F2F4F7",
  },
  inputCity: {
    height: 40,
    width: "100%",
    borderColor: "#ccc",
    backgroundColor: "#fff",
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
    borderRadius: 30,
  },
  cityPreview: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  saveButton: {
    padding: 10,
    width: "40%",
    backgroundColor: "#062C41",
    borderRadius: 30,
  },
  saveButtonText: {
    color: "#fff",
    textAlign: "center",

  },
  cancelButton: {
    padding: 10,
    width: "40%",
    backgroundColor: "#B2352E",
    borderRadius: 30,
  },
  cancelButtonText: {
    textAlign: "center",
    color: "#fff",
  },
 
  modalTitle: {
    fontWeight: "bold",
    marginBottom: 20,
  },
 
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding:30,
    paddingVertical: 90,
  },
  modalContent: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 20,
    width: "100%",  
  },
  suggestionItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  suggestionText: {
    fontSize: 14,
    color: "#333",
  },
  closeButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: "#B2352E",
    borderRadius: 30,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 16,
  },




searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    width : "100%",
    marginBottom: 15,
  },
searchButton: {
    position: "absolute",
    right:3,
    top:0,
    padding: 10,
    borderRadius: 5,
  },


  container: {
    flex: 1,
    backgroundColor: "#f9f9fb",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#062C41",  
    paddingVertical: 10,
    paddingHorizontal: 20,
    paddingTop: 45,
  },
  headerTitle: {
    fontSize: 20,
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    color: "#FFFFFC", 
    letterSpacing:2,
    fontWeight: 'bold',
    fontFamily: 'Insanibc',  
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  badge: {
    position: "absolute",
    top: -7,
    right: 2,
    backgroundColor: "red",
    borderRadius: 10,
    width: 15,
    height: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  profileContent: {
    padding: 20,
  },
  profileImageContainer: {
    alignItems: "center",  
    justifyContent: "center", 
    padding: 20,  
    backgroundColor: "#F2F4F7", 
    borderRadius: 15, 
    shadowColor: "#000", 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,  
    marginBottom: 20,  
  },
  profileImage: {
    width: 200,  
    height: 200,  
    borderRadius: 60,  
  },
  noProfileImageText: {
    color: "#999",  
    fontSize: 16,  
    fontWeight: "bold",  
    marginBottom: 20,  
  },
  updateButton: {
    marginTop: 20,
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#062C41",
    shadowColor: "#062C41",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
  updateButtonText: {
    color: "#FFFFFF",  
    fontSize: 16,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  section: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: "#fff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  field: {
    fontSize: 16,
    marginBottom: 5,
    color: "#555",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    fontSize: 16,
    color: "red",
  },
  logoutButton: {
    backgroundColor: "#e74c3c",
    shadowColor: "#e74c3c",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  logoutText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  containerPhoto: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitleProfil: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
  },
  fieldContainer: {
    marginVertical: 10,
  },
  showEmail: {
    backgroundColor: "#F2F4F7",
    justifyContent: "space-between",
    flexDirection: "row",  
    alignItems: "center",  
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 20,
    borderRadius: 50,
  },
  label: {
    fontSize: 18, 
    fontWeight: "400", 
    color: "#333", 
    marginBottom: 5, 
  }, 
  labelEmail: {
    marginTop: 5,
    flex:1,

    fontSize: 12, 
    fontWeight: "400", 
    color: "#333", 
    marginBottom: 5, 
  },
  inputContainer: {
    flexDirection: "row", 
    alignItems: "center",
    backgroundColor: "#F2F4F7",
    borderRadius: 30,
    marginTop: 5,
  },
  input: {
    flex: 1,  
    height: 40,
    marginTop: 5,
    paddingLeft: 15,
    borderRadius: 30,
  },
  icon: {
    marginRight: 15,
  },
  inputDisabled: {
    backgroundColor: "#F2F4F7",
    color: "#888",
  },
  buttonProfil: {
    padding: 15,
    borderRadius: 30,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: "#062C41",
    shadowColor: "#062C41",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
  buttonTextProfil: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  infoCardHeader: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: "#EFEFEF",
    paddingBottom: 20,
  },
  cardContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContentFollower: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 8,
    height: "50%",
    padding: 16,
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 24,
    textAlign: "center",
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  userName: {
    flex: 1,
    fontSize: 16,
  },
  unfollowButton: {
    backgroundColor: "#ff6666",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 30,
  },
  unfollowButtonText: {
    color: "#fff",
    fontSize: 14,
  },
});
