// styles/profileStyles.ts
import { StyleSheet } from "react-native";

/**
 * Styles pour l'écran de profil et ses composants
 */
export const profileStyles = StyleSheet.create({
  container: {

    paddingBottom: 30,
    backgroundColor: "#F5F5F5",
    flexGrow: 1,
  },

  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "red",
    fontSize: 16,
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#062C41",
    paddingVertical: 10,
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  headerTitle: {
    fontSize: 20,
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    color: "#FFFFFC",
    letterSpacing: 2,
    fontWeight: "bold",
    fontFamily: "Insanibc",
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  // Styles pour les modals
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContainer: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 10,
  },
  textInput: {
    borderWidth: 1,
    height: 90,
    width: "100%",
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    marginTop: 10,
    backgroundColor: "#F2F4F7",
    marginBottom: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    height: "90%",
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#333",
    textAlign: "center",
  },
  modalDescription: {
    fontSize: 14,
    textAlign: "center",
    color: "#666",
    marginBottom: 20,
  },
  modalBody: {
    width: "100%",
    paddingBottom: 10,
  },
  // Styles pour les tiers/badges
  tierCard: {
    width: 280,
    padding: 10,
    borderRadius: 30,
    alignItems: "center",
    marginBottom: 15,
  },
  tierTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
    textAlign: "center",
    padding: 15,
    width: "100%",
    borderWidth: 2,
    borderRadius: 30,
  },
  tierDescription: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  starsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: -8,
    zIndex: 1,
  },
  closeButton: {
    backgroundColor: "#062C41",
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 25,
    marginTop: 20,
    alignItems: "center",
    width: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  closeButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  // Styles pour le badge utilisateur
  badgeWrapper: {
    alignItems: "center",
  },
  iconsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 1,
    marginBottom: -17,
  },
  badgeContainer: {
    marginTop: 5,
    marginBottom: 20,
    width: "90%",
    paddingHorizontal: 20,
    height: 40,
    borderRadius: 55,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.8,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  badgeOrnement: {
    position: "absolute",
    top: 14,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  // Styles pour les boutons
  confirmButton: {
    backgroundColor: "#ff4d4f",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: "center",
    marginBottom: 10,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  confirmButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#ddd",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
  },
  cancelButtonText: {
    color: "#555",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  // Styles pour la photo de profil
  profileContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  profileImageContainer: {
    width: 150,
    height: 150,
    borderRadius: 90,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    overflow: "hidden",
  },
  profileImage: {
    width: "100%",
    height: "100%",
    borderRadius: 90,
  },
  noProfileImageText: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
  },
  goldBorder: {
    borderWidth: 5,
    borderColor: "#FFD700",
  },
  silverBorder: {
    borderWidth: 5,
    borderColor: "#C0C0C0",
  },
  bronzeBorder: {
    borderWidth: 5,
    borderColor: "#CD7F32",
  },
  medalContainer: {
    position: "absolute",
    top: -20,
    zIndex: 2,
    padding: 5,
    borderRadius: 50,
    elevation: 3,
  },
  medalText: {
    fontSize: 65,
  },
  // Styles pour les boutons d'action
  followButtonContainer: {
    width: "100%",
    alignItems: "center",
    marginVertical: 10,
  },
  followButton: {
    width: "80%",
    backgroundColor: "#062C41",
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  followButtonText: {
    textAlign: "center",
    color: "#FFF",
    fontWeight: "600",
    fontSize: 16,
  },
  sendChatContainer: {
    alignItems: "center",
    marginTop: 5,
  },
  sendChat: {
    width: "80%",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#062C41",
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
  },
  sendChatText: {
    color: "#062C41",
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  // Styles pour les cartes d'information
  infoCardContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginRight: 5,
  },
  infoValueName: {
    fontSize: 17,
    color: "#333",
    fontWeight: "600",
  },
  infoValueEmail: {
    fontSize: 17,
    color: "#333",
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  placeholderValue: {
    fontSize: 14,
    color: "#AAA",
    fontStyle: "italic",
  },
  icon: {
    marginRight: 10,
    color: "#062C41",
  },
  infoCardHeaderCity: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: "#EFEFEF",
    paddingBottom: 20,
  },
  infoCardHeader: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: "#EFEFEF",
    paddingBottom: 20,
  },
  cardContainerCity: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  cardContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  cardContent: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    flexWrap: "wrap",
    paddingHorizontal: 10,
  },
  statItem: {
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 5,
    color: "#062C41",
  },
  statLabel: {
    textAlign: "center",
    fontSize: 14,
    color: "#555",
    fontWeight: "bold",
    lineHeight: 20,
  },
  separator: {
    marginBottom: 70,
  },
  // Styles pour les onglets
  tabsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    gap: 20,
  },
  tabButton: {
    paddingVertical: 10,
  },
  tabText: {
    fontSize: 16,
    color: "#555",
  },
  activeTab: {
    borderBottomWidth: 3,
    borderBottomColor: "#57A773",
  },
  activeTabText: {
    color: "#57A773",
    fontWeight: "600",
  },
  // Styles pour les rapports/signalements
  reportCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 4,
  },
  reportImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginBottom: 8,
  },
  reportTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#666666",
    marginBottom: 10,
  },
  reportType: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "bold",
    color: "#666666",
  },
  reportTypeContainer: {
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 20,
    padding: 10,
    marginBottom: 10,
  },
  reportDescription: {
    fontSize: 14,
    color: "#7A7A7A",
    marginBottom: 10,
  },
  reportCity: {
    fontSize: 10,
    color: "#666666",
    fontWeight: "bold",
    marginBottom: 10,
  },
  reportDate: {
    fontSize: 10,
    color: "#666666",
    fontWeight: "bold",
  },
  // Styles pour les événements
  eventCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 5,
  },
  eventDescription: {
    fontSize: 14,
    color: "#666666",
    marginBottom: 10,
  },
  eventImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginBottom: 10,
  },
  eventFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#E8E8E8",
    paddingTop: 10,
  },
  eventDate: {
    fontSize: 12,
    color: "#999999",
  },
  // Styles pour messages "pas de données"
  noDataContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
  },
  noDataText: {
    fontSize: 16,
    color: '#999',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 8,
  },
  // Styles pour les publications
  postCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  profilePhoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  authorInfo: {
    marginLeft: 10,
  },
  authorName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  authorCity: {
    fontSize: 14,
    color: "#777",
  },
  postContent: {
    fontSize: 16,
    color: "#444",
    marginBottom: 15,
  },
  photosContainer: {
    flexDirection: "row",
    marginBottom: 12,
  },
  photo: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginRight: 8,
  },
  metaInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  postDate: {
    marginTop: 3,
    fontSize: 12,
    color: "#777",
  },
  likesCount: {
    fontSize: 14,
    color: "#777",
  },
  // Styles pour les commentaires
  commentsContainer: {
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 12,
  },
  commentsHeader: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    color: "#333",
  },
  comment: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginVertical: 8,
    borderBottomWidth: 1,
    paddingBottom: 10,
    borderBottomColor: "#eee",
  },
  commentProfilePhoto: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  commentContent: {
    marginLeft: 8,
    flex: 1,
  },
  commentUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  commentText: {
    fontSize: 18,
    color: "#555",
  },
  commentDate: {
    marginVertical: 2,
    fontSize: 12,
    color: "#999",
  },
  toggleCommentsButton: {
    fontSize: 14,
    color: '#57A773',
    marginTop: 5,
  },
  noCommentText: {
    fontSize: 14,
    color: '#999',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 8,
  },
  
});